### ISSUE TITLE
ADC fruit not present in Github

### ISSUE THREAD

**Issue by tsangchunsing** [ongdexter/SmartWindow#1]
unable to locate installed adcfruit files from github.

retrieved zipped version from sd card.

However, somefiles cannot be compressed and sent via email/ usb.

**Comment by ongdexter** [comment]
the files on git are those from the pi2. just add in the new ones and push them, so we can get them too.

**Comment by ongdexter** [comment]
you can try pushing directly from the pi to make things easier
